#+title: Building a blog with ~org-mode~
#+date: <2019-09-06 vie 20:00>

It has been a while since I blogged for the last time. My blog was
old, and I have been avoiding the redesign of my personal site for a very
long time now.

I don't plan to port old blog posts, so I'll [[https://oldwords.ereslibre.es][keep them as they are]].

I wanted something simple, where I could write my thoughts as raw
as possible. Luckily, I have been doing so for a long time using
~emacs~'s ~org-mode~ for everything personal and work related. It has
made a difference in the way I organize, and thought it would be a
good idea to apply the very same principles to my website and blog. So
here we are.

I had some fun along the way with emacs lisp and I'll explain a little
what I think are the most important points of my setup.

* Notes

Notes are pages meant to be alive and changing over time. Annotations
for my future self mainly; posted in the public just in case they help
someone else. Undated.

* Blog

Exactly. Blog posts are what you think they are. Once published, not usually
updated over time. Dated.

* Front page

The front page is really simple: it contains a list of all the notes
and blog entries.

It is dynamically generated from the structure of the project.

* RSS

RSS is an XML feed that only applies to blog posts. It is dynamically
generated as well.

* Arbitrary static pages

The [[file:../../../contact.org][contact page]] is a good example of an arbitrary static page.

These pages are not included in the list of blog posts or notes. They
are linked from the template.

-----

@@html:<i class="fab fa-github"></i>@@ GitHub repository: [[https://github.com/ereslibre/ereslibre.es][https://github.com/ereslibre/ereslibre.es]]

@@html:<i class="fas fa-link"></i>@@ Old blog posts: [[https://oldwords.ereslibre.es][https://oldwords.ereslibre.es]]
